### ISSUE TITLE
Julia package?!

### ISSUE THREAD

**Issue by PallHaraldsson** [ceferisbarov/hijri-converter#1]
A. I would change "A Python package"->"A package" (given "Julia 100.0%"), or maybe state somewhere (ported from the Python package XXX" if that's what you meant. It doesn't seem to be a wrapper, I didn't notice e.g. PyCall.jl used.

B. You likely want to add a license. I believe this package is already registered, and I understood an OSI-compatible license a requirement.

**Comment by ceferisbarov** [comment]
A. I will fix this in the next commit. Thanks.
B. I have already added MIT license, although Julia Hub does not display it. I do not understand the problem.
